sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        Opr2rXE6H7LO5tf2h9NBF7qasopGiL8YWziSnnZsFoerPL2V1/rXc6TZmGCP6IzL8sgYJlwZ7A3HdeX1vAd4U6/n0p4GV1W4Afex1aQBxNQedRkTQM9FzAvXgaKQTLLYY3A4npm19mI4gXMXQGJvbHqQOj4juo/oCrFDQ+Jcix1s14DXd4JwuBjDIFqVB2Hon7D/boMBYHchgVrzcr1Ha9MMlZ2KnBkUx2jKFGG5oKN2vA1J9cb6cEllPyJOyGa1NLdk+wrMdeXai4HXEEgQdKzd0XTE2qsgXOB55ReeW2j+3Jv1ZvHi+6TvZ+fAV1w3eLEu9S/zMui1rEBXh4sFoBCeicfTGm7LXChYkIlC6TiovLkv8SXWB6lNHJXPblAt/4UUbgydd0+2LDpnlki7mAR03c494zXqPhfMlxSsJuGfyx2PW98c627JxDUUepHEjqRhNjiBtV/LqcXQ2YVRR+RPGICGWrzT/oIhW7SsIWRFTULKviwrf+0YsEevq2Vq3g5TEwKVcRfVl3vnxnnqGcdflTpTONNFyFwBqvix8RWJLQyjKBzO9W5NTDwefGuNTi/cQPHAQbl2/1ON8ag6wsmoT1C5RYJ/849z0UoMVyO23vXNcUATGXR/ft9aDl1JSHfxfhlfO8XCJOoRuVW/avaJbFmBgEu5ySOhL61QN6w=
    - secure: >-
        StESyHWS57sTJT9qqsbjdt++uXJ7/nU4FDdulH3N6jXWxO2+ozG+UqcukJreHkNXhSJtXvnzmz0iatCFR7wMxxZr+E4F7U5+9SQChcC4x5uTX2RJKTZOXGvQEo8btsoTvyuGdrsmQsoN0Baxrz3sPigFMHlsqxgob00wfnnuZOhAF+iaInYIDd0nACwJSokaN808L9hiRUpVqKfJ9HJOdZRUfA3E6hQoCv96OwAoYYKSf1QFklowquLBh+zdQ1HqxyecqxNmO6FG99Jzq+vBWA74EvSeU4NXS/Ts0ItKryV4XKz7imwlb1cW34zU3UoPLHhfDEvsOZQWQxQMNAMeVUbf+SLMvRtqUm5I5NiFWTDdXric8gNh49nEDGFPfDXqwCH1rkD1cI1qEBtYr9+fnTbJo4fI/C1rt55JG92eqJecSH88kfXfP8gQYleLtpgdaSF0rviP+NuHws6hKFTjYmazQ0RpxidD30wGePxxCYq/ep+3aTrb8MdemlGAOGC4aYG961aYpsSwWhlbxY2VsI0vZQm+ihWtlwVJBAuu8gYl8wWz4xeWO83lia7qAyY0y9nUyCOMfT1agVsV/arFbyGnG7awUfdRDVdLeO9hNYI707U5UzQEhrQlWKaf6jWcYQvavDRRrEvVIYBh1TpmcTHYHc3JeBRiPp33WoXYTIE=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
